name: flutter_dsfr
description: "Système de Design de l'État français en flutter"
version: 0.1.0
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.19.0

dev_dependencies:
  custom_lint:
  dsfr_lints:
    path: ./tools/dsfr_lints
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  meta: ^1.1.8

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Marianne
      fonts:
        - asset: assets/fonts/Marianne-Light.otf
          weight: 300
        - asset: assets/fonts/Marianne-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Marianne-Regular.otf
          weight: 400
        - asset: assets/fonts/Marianne-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Marianne-Medium.otf
          weight: 500
        - asset: assets/fonts/Marianne-Bold.otf
          weight: 700
        - asset: assets/fonts/Marianne-BoldItalic.otf
          weight: 700
          style: italic
    - family: DsfrIcons
      fonts:
        - asset: assets/icons/Dsfr-Icons.otf
